/**
 * Defines a base OthelloPlayer class that specifies the board and token.
 *
 * @author  T.Sergeant
 * @version For AI
 *
*/
public abstract class OthelloPlayer
{
	protected Board board; // the board the player is using
	protected char token;  // the token the player is using
	protected int win;
	protected int lose;

	/**
	 * Set the board and token.
	 */
	public OthelloPlayer(Board board, char token)
	{
		this.board= board;
		this.token= token;
		win = 0;
		lose = 0;
	}

	/**
	 * We represent the player by their token.
	 */
	@Override
	public String toString()
	{
		return ""+token;
	}

	/**
	 * Every OthelloPlayer needs to specify how they will make a move.
	 *
	 * <p>This method will need to call board.makeMove() as part of it's
	 * action to update the board and to get a valid Move object.</p>
	 *
	 * @return a Move object generated by board.makeMove()
	 */
	public abstract Move makeMove();
	
	
	/**
	 * Method used to determine what piece won.
	 * @param token we are comparing if they won or not
	 * @return
	 */
	public char whoWon(char token){
		int xcount = 0;
		int ocount = 0;
		for(int i=0; i<8; i++){
			for(int j=0; j<8; j++){
				if(board.grid[i][j] == 'X')
					xcount++;
				if(board.grid[i][j] == 'O')
					ocount++;
			}
		}
		if(xcount > ocount) return 'X';
		else return 'O';
	}
}
